export default {
<<<<<<< HEAD
    ON_LOGIN_SUCCESS: "ON_LOGIN_SUCCESS",
    ON_LOGIN_FAIL: "ON_LOGIN_FAIL",
    ON_LOGOUT_SUCCESS: "ON_LOGOUT_SUCCESS",
    ON_REGISTER_FAIL: "ON_REGISTER_FAIL"

}
=======
  ON_LOGIN_SUCCESS: "ON_LOGIN_SUCCESS",
  ON_LOGIN_FAIL: "ON_LOGIN_FAIL",
  ON_LOGOUT_SUCCESS: "ON_LOGOUT_SUCCESS",
};
>>>>>>> 6dba32738aaf227d6a159edcd2d87bf720b06f33
